import React from 'react';
import { CheckCircle2, ShieldCheck, Target, Sparkles, BookOpen, Layers, Link2, Image as ImageIcon, Smile } from 'lucide-react';

interface SeoRulesVerificationViewProps {
  onGoToGenerator: () => void;
}

export const SeoRulesVerificationView: React.FC<SeoRulesVerificationViewProps> = ({
  onGoToGenerator,
}) => {
  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Header */}
      <div className="bg-white rounded-2xl border border-stone-200 p-6 shadow-sm">
        <div className="flex items-center space-x-2 text-xs font-semibold text-emerald-800 bg-emerald-50 px-3 py-1 rounded-full w-fit border border-emerald-200 mb-2">
          <ShieldCheck className="w-3.5 h-3.5" />
          <span>Strict Algorithm & Architectural Specs</span>
        </div>
        <h2 className="text-xl sm:text-2xl font-bold text-stone-900 font-serif">
          Strict SEO Constraint Rules & Dashboard Architecture
        </h2>
        <p className="text-sm text-stone-600 mt-1">
          Every full article generated by BlogPulse AI strictly adheres to these three golden algorithmic rules and dashboard standards.
        </p>
      </div>

      {/* 3 Core Rules Card */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Rule 1 */}
        <div className="bg-white p-6 rounded-2xl border border-stone-200 shadow-sm space-y-3 relative overflow-hidden">
          <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-800 border border-amber-200 flex items-center justify-center font-bold font-serif text-lg">
            01
          </div>
          <h3 className="font-bold text-stone-900 text-base font-serif">
            Focus Keyword in Title
          </h3>
          <p className="text-xs text-stone-600 leading-relaxed">
            The primary focus keyword is verbatim or naturally embedded in the main H1 headline, ensuring maximum search engine indexing signals and click-through relevance.
          </p>
          <div className="bg-stone-50 p-2.5 rounded-lg border border-stone-200 text-[11px] font-mono text-emerald-800 flex items-center space-x-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>&lt;h1&gt;[Focus Keyword]...&lt;/h1&gt;</span>
          </div>
        </div>

        {/* Rule 2 */}
        <div className="bg-white p-6 rounded-2xl border border-stone-200 shadow-sm space-y-3 relative overflow-hidden">
          <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-800 border border-amber-200 flex items-center justify-center font-bold font-serif text-lg">
            02
          </div>
          <h3 className="font-bold text-stone-900 text-base font-serif">
            Focus Keyword in Meta Description
          </h3>
          <p className="text-xs text-stone-600 leading-relaxed">
            The meta description (constrained between 140–160 characters) contains the exact focus keyword within a compelling, high-converting snippet summary.
          </p>
          <div className="bg-stone-50 p-2.5 rounded-lg border border-stone-200 text-[11px] font-mono text-emerald-800 flex items-center space-x-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>&lt;meta name="description" ...&gt;</span>
          </div>
        </div>

        {/* Rule 3 */}
        <div className="bg-white p-6 rounded-2xl border border-stone-200 shadow-sm space-y-3 relative overflow-hidden">
          <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-800 border border-amber-200 flex items-center justify-center font-bold font-serif text-lg">
            03
          </div>
          <h3 className="font-bold text-stone-900 text-base font-serif">
            Focus Keyword in 1st Sentence of 1st Paragraph
          </h3>
          <p className="text-xs text-stone-600 leading-relaxed">
            The very first sentence of the opening paragraph immediately establishes thematic authority by explicitly incorporating the focus keyword in the hook.
          </p>
          <div className="bg-stone-50 p-2.5 rounded-lg border border-stone-200 text-[11px] font-mono text-emerald-800 flex items-center space-x-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>&lt;p&gt;Sentence 1: [Focus Keyword]...&lt;/p&gt;</span>
          </div>
        </div>
      </div>

      {/* Dashboard Features Breakdown */}
      <div className="bg-stone-900 text-white rounded-2xl p-6 sm:p-8 space-y-6">
        <h3 className="text-xl font-bold font-serif text-amber-300 flex items-center space-x-2">
          <Sparkles className="w-5 h-5 text-amber-400" />
          <span>Complete System Capabilities</span>
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
          <div className="bg-stone-800/80 p-4 rounded-xl border border-stone-700 space-y-2">
            <div className="flex items-center space-x-2 text-stone-200 font-bold text-sm">
              <Smile className="w-4 h-4 text-emerald-400" />
              <span>Sentiment Analysis Scoring</span>
            </div>
            <p className="text-stone-300 leading-relaxed">
              Every curated article calculates a multi-factor sentiment score (-1.0 to +1.0), subjective/objective ratio, tone classification, and emotional drivers.
            </p>
          </div>

          <div className="bg-stone-800/80 p-4 rounded-xl border border-stone-700 space-y-2">
            <div className="flex items-center space-x-2 text-stone-200 font-bold text-sm">
              <ImageIcon className="w-4 h-4 text-amber-400" />
              <span>Related Image Summaries & Prompts</span>
            </div>
            <p className="text-stone-300 leading-relaxed">
              Visual theme definitions, Midjourney/Gemini image generation prompts, aspect ratio specifications, and SEO alt texts for all articles.
            </p>
          </div>

          <div className="bg-stone-800/80 p-4 rounded-xl border border-stone-700 space-y-2">
            <div className="flex items-center space-x-2 text-stone-200 font-bold text-sm">
              <Link2 className="w-4 h-4 text-cyan-400" />
              <span>Backlink Graph & Context Anchors</span>
            </div>
            <p className="text-stone-300 leading-relaxed">
              Discovers canonical authority links, estimated Domain Authority (DA), and contextual anchor texts for seamless backlink integration.
            </p>
          </div>

          <div className="bg-stone-800/80 p-4 rounded-xl border border-stone-700 space-y-2">
            <div className="flex items-center space-x-2 text-stone-200 font-bold text-sm">
              <BookOpen className="w-4 h-4 text-rose-400" />
              <span>Full Blog Post Generation</span>
            </div>
            <p className="text-stone-300 leading-relaxed">
              Deep, comprehensive markdown and HTML posts with Table of Contents, FAQ schemas, key takeaways, and live SEO checklist verification.
            </p>
          </div>
        </div>

        <div className="pt-2 flex justify-center">
          <button
            onClick={onGoToGenerator}
            className="px-6 py-3 bg-amber-400 hover:bg-amber-300 text-stone-900 font-bold text-sm rounded-xl transition-all shadow-md cursor-pointer flex items-center space-x-2"
          >
            <BookOpen className="w-4 h-4" />
            <span>Launch Complete Blog Studio</span>
          </button>
        </div>
      </div>
    </div>
  );
};
